name: Send GIF Email

on:
  workflow_dispatch:  # запуск вручную
  repository_dispatch: 
  # schedule:
  #   - cron: '* * * * *'  # ежедневно в 08:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest

    env:  # передаём секреты в Python
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}
      GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py
