name: Send GIF Email

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установить зависимости
        run: pip install -r requirements.txt

      - name: Запустить скрипт
        run: python main.py